<Container>
    orientation: "vertical"
    Label:
        text: "Welcome, name!"
    Button:
        id: buttonWeather
        text:"Weather"
    Button:
        id: buttonTwitter
        text:"Twitter"
    Button:
        id: buttonNotes
        text:"Notes"
    Button:
        id: buttonReminders
        text:"Reminders"
    Button:
        id: buttonAlarms
        text:"Alarms"
    Button:
        id: buttonSettings
        text:"Settings"